version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing npm dependencies.
      - npm ci
  build:
    commands:
      - echo Build started
      - npm run build
      - npm run test-unit
      - export BUCKET=codepipeline-eu-central
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - echo Build completed
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
