version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing npm dependencies.
      - npm ci
  build:
    commands:
      - echo Build started
      - npm run build
      - npm run test-unit
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - index.js
    - dist/**/*
    - request-map.js
    - credentials.json
    - node_modules/**/*
