AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  SaveExeuctionPlanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambdas/
      Handler: saveExecutionPlanLambda.handler
      Runtime: nodejs10.x
